# Generated by Django 5.0.7 on 2024-07-31 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.BooleanField(default=False)),
                ('wheels', models.BooleanField(default=False)),
                ('animals', models.BooleanField(default=False)),
                ('braille', models.BooleanField(default=False)),
                ('elevators', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
