# Generated by Django 5.0.7 on 2024-07-31 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usermapsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=1023)),
                ('end', models.CharField(max_length=1023)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
